# Generated by Django 4.1.5 on 2023-03-30 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grocery', '0003_customerprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customerprofile',
        ),
    ]
