# Generated by Django 4.1.5 on 2023-04-26 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grocery', '0005_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='Userid',
            new_name='First_Name',
        ),
    ]
