# Generated by Django 4.1.5 on 2023-04-26 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grocery', '0006_rename_userid_review_first_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='First_Name',
            new_name='Userid',
        ),
    ]
