# Generated by Django 4.1.5 on 2023-05-09 05:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0036_alter_category_register_date_and_more'),
        ('grocery', '0009_fav'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fav',
            name='Productid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='dashboard.product'),
        ),
    ]
