# Generated by Django 4.1.5 on 2023-03-14 07:59

import datetime
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category_Name', models.CharField(max_length=100)),
                ('Date', models.DateField(default=datetime.date(2023, 3, 14))),
                ('Status', models.CharField(default='inactive', max_length=50)),
            ],
            options={
                'db_table': 'Category',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Photo', models.ImageField(upload_to='product1/')),
                ('Product_Name', models.CharField(max_length=100)),
                ('MRP', models.FloatField(default=0.0)),
                ('Selling_Price', models.FloatField()),
                ('Opening_Stock', models.FloatField()),
                ('Date', models.DateField(default=datetime.date(2023, 3, 14))),
                ('Status', models.CharField(choices=[('Coming Soon', 'Coming Soon'), ('InStock', 'InStock'), ('Available', 'Available'), ('Out of Stock', 'Out of Stock')], max_length=100)),
                ('Description', tinymce.models.HTMLField()),
                ('Categoryid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.category')),
            ],
            options={
                'db_table': 'Product',
            },
        ),
    ]
