# Generated by Django 4.1.5 on 2023-03-15 06:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='Date',
            field=models.DateField(default=datetime.date(2023, 3, 15)),
        ),
        migrations.AlterField(
            model_name='product',
            name='Date',
            field=models.DateField(default=datetime.date(2023, 3, 15)),
        ),
    ]
