# Generated by Django 4.1.5 on 2023-03-15 06:34

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_category_date_alter_product_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Supplier_Name', models.CharField(max_length=50)),
                ('Register_Date', models.DateField(default=datetime.date(2023, 3, 15))),
                ('Email', models.CharField(max_length=100)),
                ('Phone_No', models.CharField(max_length=20)),
                ('Productid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.product')),
            ],
            options={
                'db_table': 'Supplier',
            },
        ),
    ]
