# Generated by Django 4.1.5 on 2023-03-15 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_supplier'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='Date',
            new_name='Register_Date',
        ),
    ]
