# Generated by Django 4.1.5 on 2023-03-15 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_purchase'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='purchase',
            table='Purchase',
        ),
    ]
