# Generated by Django 4.1.5 on 2023-03-16 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_alter_category_register_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='Pic',
            field=models.ImageField(default='', upload_to='category/'),
        ),
    ]
