# Generated by Django 4.1.5 on 2023-03-30 06:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_alter_category_register_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employeprofile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Picture', models.ImageField(upload_to='')),
                ('Employe_Name', models.CharField(max_length=50)),
                ('Username', models.CharField(max_length=100)),
                ('Gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=50)),
                ('Date_Of_Join', models.DateField(default=datetime.date(2023, 3, 30))),
                ('Contact_No', models.CharField(max_length=12)),
                ('Email', models.CharField(max_length=100)),
                ('Address', models.TextField()),
            ],
            options={
                'db_table': 'Employeprofile',
            },
        ),
        migrations.AlterField(
            model_name='category',
            name='Register_Date',
            field=models.DateField(default=datetime.date(2023, 3, 30)),
        ),
        migrations.AlterField(
            model_name='product',
            name='Register_Date',
            field=models.DateField(default=datetime.date(2023, 3, 30)),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='Date',
            field=models.DateField(default=datetime.date(2023, 3, 30)),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='Register_Date',
            field=models.DateField(default=datetime.date(2023, 3, 30)),
        ),
    ]
