# Generated by Django 4.1.5 on 2023-04-04 06:34

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0012_employeprofile_alter_category_register_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeprofile',
            name='Employe_Id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='category',
            name='Register_Date',
            field=models.DateField(default=datetime.date(2023, 4, 4)),
        ),
        migrations.AlterField(
            model_name='employeprofile',
            name='Date_Of_Join',
            field=models.DateField(default=datetime.date(2023, 4, 4)),
        ),
        migrations.AlterField(
            model_name='product',
            name='Register_Date',
            field=models.DateField(default=datetime.date(2023, 4, 4)),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='Date',
            field=models.DateField(default=datetime.date(2023, 4, 4)),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='Register_Date',
            field=models.DateField(default=datetime.date(2023, 4, 4)),
        ),
    ]
