# Generated by Django 4.1.5 on 2023-04-13 14:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0016_alter_category_register_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='Supplier_Pic',
            field=models.ImageField(default='', upload_to='supplier/'),
        ),
        migrations.AlterField(
            model_name='category',
            name='Register_Date',
            field=models.DateField(default=datetime.date(2023, 4, 13)),
        ),
        migrations.AlterField(
            model_name='employeprofile',
            name='Date_Of_Join',
            field=models.DateField(default=datetime.date(2023, 4, 13)),
        ),
        migrations.AlterField(
            model_name='employeprofile',
            name='Picture',
            field=models.ImageField(default='', upload_to='employeprofile/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='Register_Date',
            field=models.DateField(default=datetime.date(2023, 4, 13)),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='Date',
            field=models.DateField(default=datetime.date(2023, 4, 13)),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='Register_Date',
            field=models.DateField(default=datetime.date(2023, 4, 13)),
        ),
    ]
