# Generated by Django 4.1.5 on 2023-04-15 05:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0019_alter_category_register_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='Employeprofileid',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='purchase',
            name='MRP',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='purchase',
            name='Payment_Status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed'), ('Waiting', 'Waiting'), ('Decline', 'Decline')], default='', max_length=50),
        ),
        migrations.AddField(
            model_name='purchase',
            name='Purchase_Status',
            field=models.CharField(choices=[('Item Recived', 'Item Recived'), ('Not recived', 'Not Recived')], default='', max_length=50),
        ),
        migrations.AddField(
            model_name='purchase',
            name='Total',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
