# Generated by Django 4.1.5 on 2023-04-17 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0022_alter_category_register_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeprofile',
            name='Employe_Id',
        ),
    ]
