# Generated by Django 4.1.5 on 2023-04-17 14:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0023_remove_employeprofile_employe_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeprofile',
            name='Employe_Id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
