# Generated by Django 4.1.5 on 2023-04-21 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0027_remove_supplier_productid_supplier_categoryid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchase',
            old_name='Supplierid',
            new_name='Categoryid',
        ),
    ]
