# Generated by Django 4.1.5 on 2023-04-22 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0030_rename_categoryid_purchase_supplierid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='Payment_Status',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='Purchase_Status',
            field=models.CharField(default='', max_length=50),
        ),
    ]
