# Generated by Django 4.1.5 on 2023-04-16 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_userid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='Userid',
        ),
    ]
