# Generated by Django 4.1.5 on 2023-05-11 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_order_userid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='Userid',
            new_name='userid',
        ),
    ]
